### ISSUE TITLE
Add customisable university name feature

### ISSUE THREAD

**Issue by jamietopp21** [brudil/upstanding#16]

**Comment by brudil** [comment]
If you could write out a list of textual replacements you would like that would be super helpful! For instance we might want {uni:vice} and {uni:nightclub} {uni:name} {uni:location}. I guess it's a balance between unique-ness of the article and effort having to research this info for every uni we add.

We also might want to think about if we can have generic replacements that would still make sense if someone hasn't selected a uni.

**Comment by jamietopp21** [comment]
I would say the best way to approach this would be to start only have the University names, saves research. We could store them all in this format with a space at each end and also have a blank name stored (just a space):
" Sussex "
" Brighton "
" "
then when we wish to use them we might type
"It was found out that a{uni:name}student has passed their degree"
this way if no university has been selected we can just replace {uni:name} with the space. 

As for future text replacements
University Name i.e Sussex
University vVce Chancellor i.e Adam Tickell
Local club i.e. Pryzm
Campus locations i.e East Slope Accomidation, Falmer Bar, URF
