### ISSUE TITLE
Change headline typeface to something slightly easier to read

### ISSUE THREAD

**Issue by jamietopp21** [brudil/upstanding#17]
The current font is a little groovy I would say

**Comment by brudil** [comment]
While I have no particular love of this typeface, I'd argue the headline typeface needs to be unique and bold-ish as it will be a large part of the brands identity. 

If you've like to have a look a the available web fonts on Typekit.com and see if there is something there you like the look of.

**Comment by jamietopp21** [comment]
Will do! Yeah a recognisable font is certainly important - but I feel this font is a bit too in your face in terms of design
