### ISSUE TITLE
Add rounded corners to images

### ISSUE THREAD

**Issue by jamietopp21** [brudil/upstanding#20]
Nice and subtle, but would make the site feel a bit more modern/organic and feel less blocky/pointy

**Comment by brudil** [comment]
Is it fair to say we are not aiming to parody the tab site in the slightest
then? Purely asking as the tab site goes for a more sharp style

**Comment by jamietopp21** [comment]
I wouldn't say that, it's just my personal preference for look to be honest, we're still called "The Drab" and will have an incredibly similar format. Plus I was only talking about having incredibly subtle corners, just to smooth things out the tiniest amount
