### ISSUE TITLE
Add author to articles on homepage

### ISSUE THREAD

**Issue by jamietopp21** [brudil/upstanding#21]

**Comment by brudil** [comment]
From the design, I was planning we do this selectively as not to clutter the page with too much information.

Viewpoint/opinion conten gets a byline on the homepage, where as other content doesn't.

Thoughts.

**Comment by jamietopp21** [comment]
I think it should be consistent within each category, i.e as you say opinion content gets a byline, quizzes formatted the same, news formatted the same, but I think if we can find room for a "by Stephen Weybridge" next to articles we should implement it

**Comment by brudil** [comment]
The Guardian do some cool stuff here, have a look at how different colors and layouts relate the the tones, types and topic of the content. https://www.theguardian.com/uk

**Comment by jamietopp21** [comment]
Yes if we have authors names by opinions/reviews/guides and things of that nature, for stuff like news and interactives it's not necessary really. Although personally I'm not sure about the quotation mark.

Agree with the kickers, should we impliment the standalone somewhere? perhaps on the article page above the picture?

I like the pink and blue for quizzes and interactive, it makes them stand out
